#!/usr/bin/env bash

# SCRIPT VERSION
CUSTOM_SETUP_VER=1
CUSTOM_SETUP_VER_FILE="/etc/ublue/custom-setup"
CUSTOM_SETUP_VER_RAN=$(cat "$CUSTOM_SETUP_VER_FILE")

# make the directory if it doesn't exist
mkdir -p /etc/ublue

# Run script if updated
if [[ -f $CUSTOM_SETUP_VER_FILE && "$CUSTOM_SETUP_VER" = "$CUSTOM_SETUP_VER_RAN" ]]; then
  echo "Custom setup has already run. Exiting..."
  exit 0
fi

# Function to append a group entry to /etc/group
append_group() {
  local group_name="$1"
  if ! grep -q "^$group_name:" /etc/group; then
    echo "Appending $group_name to /etc/group"
    grep "^$group_name:" /usr/lib/group | tee -a /etc/group >/dev/null
  fi
}

# Setup Groups
append_group docker

wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr ',' '\n'))
for user in $wheelarray; do
  usermod -aG docker $user
done

# Prevent future executions
echo "Writing state file"
echo "$CUSTOM_SETUP_VER" >"$CUSTOM_SETUP_VER_FILE"
