#!/usr/bin/env bash

# SCRIPT VERSION
CUSTOM_SETUP_VER=1
CUSTOM_SETUP_VER_FILE="/etc/ublue/custom-setup"
CUSTOM_SETUP_VER_RAN=$(cat "$CUSTOM_SETUP_VER_FILE")

# make the directory if it doesn't exist
mkdir -p /etc/ublue

# Run script if updated
if [[ -f $CUSTOM_SETUP_VER_FILE && "$CUSTOM_SETUP_VER" = "$CUSTOM_SETUP_VER_RAN" ]]; then
  echo "Custom setup has already run. Exiting..."
  exit 0
fi

wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr ',' '\n'))
for user in $wheelarray; do
  usermod -aG docker $user
done

# Prevent future executions
echo "Writing state file"
echo "$CUSTOM_SETUP_VER" >"$CUSTOM_SETUP_VER_FILE"
